kind: pipeline
type: docker
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: reg.s-c.systems
    username:
      from_secret: registry_user
    password:
      from_secret: registry_password
    repo: reg.s-c.systems/pr0/pr0music
    auto_tag: true

trigger:
  branch:
  - master
  event:
  - tag